name: Pipeline com ls

on: [push]

jobs:
  listar-arquivos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Listar arquivos do repositório
        run: ls -la
